#!/usr/bin/env bash
# Script prints numbers from 1 to 100 and on every multiple of 3 it prints fizz,
on every multiple of 5 prints buzz and every combination ob both prints fizzbuzz
counter=1
while [[ $counter -le 100 ]]
do
	if [[ $(( counter % 3 )) == 0 ]] && [[ $(( counter % 5 )) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $(( counter % 3)) == 0 ]]
	then
		echo "Fizz"
	elif [[ $(( counter % 5)) == 0 ]]
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
	counter=$(( counter + 1 ))
done
