#!/usr/bin/env bash
# script prints holberton school except on the 9th line
counter=1
while [ $counter -le 10 ]
do
	echo "Holberton School"
	if [[ $counter -eq 9 ]]
	then
		echo "Hi"
	fi
	counter=$(( counter + 1 ))
done
