#!/usr/bin/env bash
# script prints holberton school except on the 4th and 8th line
counter=1
while [[ $counter -le 10 ]]
do
	if [[ $counter -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $counter -eq 8 ]]
	then
		echo "good luck"
	else
	        echo "Holberton School"
	fi

	counter=$(( counter + 1 ))
done
