#!/usr/bin/env bash
# script prints numbers from 1 to 20 except on lines 4, 9, 17
counter=1
while [[ $counter -le 20 ]]
do
	if [[ $counter -eq 4 ]]
	then
		echo "bad luck from China"
	elif [[ $counter -eq 9 ]]
	then
		echo "bad luck from Japan"
	elif [[ $counter -eq 17 ]]
	then
		echo "bad luck from Italy"
	else
	        echo "$counter"
	fi
	counter=$(( counter + 1 ))
done
