#!/usr/bin/env bash
# script prints numbers from 1 to 20, after lines 4, 9, 17 prints a bad luck message
counter=1
while [[ $counter -le 20 ]]
do
	echo "$counter"
	case $counter in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac

	counter=$(( counter + 1 ))
done
