#!/usr/bin/env bash
# script configures firewall for all port except 22, 443, 80
sudo apt-get install -y
sudo apt-get install -y ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
